{
  imports = [
    ./akkoma.nix
    ./audiobookshelf.nix
    ./backups.nix
    ./gollum.nix
    ./hass.nix
    ./immich.nix
    ./jackett.nix
    ./jellyfin.nix
    ./lidarr.nix
    ./lubelogger.nix
    ./matrix-synapse.nix
    ./miniflux.nix
    ./misc.nix
    ./nginx.nix
    ./openwebui.nix
    ./peggy.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./sabnzbd.nix
    ./samba.nix
    ./sonarr.nix
    ./stirling-pdf.nix
    ./syncthing.nix
    ./traefik.nix
    ./transmission.nix
    ./uptime-kuma.nix
    ./vaultwarden.nix
  ];
}
