{
  imports = [
    ./akkoma.nix
    ./audiobookshelf.nix
    ./backups.nix
    ./dashboard.nix
    ./diun.nix
    ./esp-sync.nix
    ./flake-lock-update.nix
    ./forgejo.nix
    ./gatus.nix
    ./gollum.nix
    ./hass.nix
    ./immich.nix
    ./installer-iso.nix
    ./jackett.nix
    ./jellyfin.nix
    ./lan-proxy.nix
    ./lubelogger.nix
    ./matrix-synapse.nix
    ./miniflux.nix
    ./misc.nix
    ./nextcloud.nix
    ./nginx.nix
    ./nix-cache.nix
    ./peggy.nix
    ./permissions.nix
    ./pinchflat.nix
    ./postgresql.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./sabnzbd.nix
    ./samba.nix
    ./seerr.nix
    ./sonarr.nix
    ./stirling-pdf.nix
    ./syncthing.nix
    ./today.nix
    ./traefik.nix
    ./transmission.nix
    ./unpackerr.nix
    ./vaultwarden.nix
  ];
}
