{
  imports = [
    ./ai.nix
    ./bash.nix
    ./bemenu.nix
    ./calendar.nix
    ./catppuccin.nix
    ./fonts.nix
    ./foot.nix
    ./git.nix
    ./gpg.nix
    ./imv.nix
    ./mail.nix
    ./mpv.nix
    ./neomutt.nix
    ./nix.nix
    ./notmuch.nix
    ./packages.nix
    ./pianobar.nix
    ./ruff.nix
    ./ssh.nix
    ./stow.nix
    ./tmux.nix
    ./udiskie.nix
    ./uv.nix
    ./watson.nix
    ./xdg.nix
    ./yazi.nix
    ./ydotool.nix
    ./zoxide.nix
  ];
}
