{
  imports = [
    ./airvpn-port-check.nix
    ./authelia.nix
    ./backups.nix
    ./bfd-services.nix
    ./gatus.nix
    ./grafana.nix
    ./proxy-me.nix
    ./microbin.nix
    ./mysql.nix
    ./nextcloud.nix
    ./nginx.nix
    ./permissions.nix
    ./prometheus.nix
    ./rustdesk.nix
    ./searx.nix
    ./syncthing.nix
    ./syncthing-discovery.nix
    ./traefik.nix
  ];
}
